services:
  strato_bot:
    container_name: strato_bot
    build: .
    restart: always
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://api.telegram.org/bot$BOT_TOKEN/getMe || exit 1"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    labels:
      com.docker.compose.service: "stratobot"
  
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml  
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    restart: always
    env_file:
      - .env
